import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Banner from '../components/banner';
import Image from "next/image";
import Card from '../components/card';
import fetchCoffeeStores from '../lib/coffee-store';

export async function getStaticProps(context) {
  const coffeeStores = await fetchCoffeeStores();
  return {
    props: {
      coffeeStores: coffeeStores,
    },
  };
}

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    alert('test');
  }
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick} />
        <div className={styles.bannerImage}>
          <Image alt='bannerBackgroud' src="/static/backgound-banner.png" width={700} height={400} />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
          
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map(coffeeStore => {
                return (
                    <Card
                    key={coffeeStore.fsq_id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl || "https://images.unsplash.com/photo-1498804103079-a6351b050096?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2468&q=80"}
                    href={`/coffee-store/${coffeeStore.fsq_id}`}
                    className={styles.card} />
                  );
              })}
            </div>
          </>
        )}
      </main>
    </>
  )
}
